version: '3'
services:
  db:
    container_name: db_postgres
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    user: postgres  
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      start_period: 10s
      timeout: 4s
      retries: 3         
    networks:
      - application-network            

  server:
    container_name: server_backend
    build: .       
    ports:
      - "3333:3333"   
    networks:
      - application-network  
    depends_on:
      db:
        condition: service_healthy        

networks:
  application-network: